# Can be rendered using PlantUML extension in VS Code

@startuml
    title Start outgoing call, then end call
    participant "Softphone" as phone
    participant "Jabra SDK" as sdk
    participant "Jabra Device" as device
    phone->sdk: getLockAsync()
    sdk->phone:
    Activate phone
    note over phone: Call lock acquired
    phone->sdk: offhookAsync()
    sdk->device: OffHook=1
    device->sdk: OffHook=1
    note over device: Device goes into call state
    sdk->phone: btnPress\n(OffHook, true)
    phone->sdk: onhookAsync()
    sdk->device: OffHook=0
    device->sdk: OffHook=0
    note over device: Device goes out of call state
    sdk->phone: btnPress\n(OffHook, false)
    phone->sdk: releaseLockAsync()
    Deactivate phone
    sdk->phone:
@enduml

@startuml
    title Incoming call accepted on device, then ended on device
    participant "Softphone" as phone
    participant "Jabra SDK" as sdk
    participant "Jabra Device" as device
    Actor User as user
    -> phone: Incoming call
    phone->sdk: getLockAsync()
    sdk->phone:
    Activate phone
    note over phone: Call lock acquired
    phone->sdk: ringAsync()
    sdk->device: Ring=1
    note over device: Device starts ringer
    user->device: Press accept call button
    device->sdk: OffHook=1
    sdk->phone: btnPress\n(OffHook, true)
    phone->sdk: offhookAsync()
    sdk->device: OffHook=1
    phone->sdk: unringAsync()
    sdk->device: Ring=0
    note over device: Device stops ringer\nand goes into call state
    ...
    user->device: Press end call button
    device->sdk: OffHook=0
    sdk->phone: btnPress\n(OffHook, false)
    phone->sdk: onhookAsync()
    sdk->device: OffHook=0
    note over device: Device leaves call state
    phone->sdk: releaseLockAsync()
    Deactivate phone
    sdk->phone:
@enduml

@startuml
    title Incoming call rejected on device
    participant "Softphone" as phone
    participant "Jabra SDK" as sdk
    participant "Jabra Device" as device
    Actor User as user
    -> phone: Incoming call
	phone -> sdk: getLockAsync()
	sdk -> phone:
	Activate phone
    Note over phone: Call lock acquired
    phone -> sdk: ringAsync()
    sdk -> device: Ring=1
    Note over device: Ringer starts
    user -> device: Reject call by double-pressing\nthe multi-function button
    device -> sdk: HID: Reject Call
    sdk -> phone: btnPress\n(RejectCall, true)
    phone -> sdk: unringAsync()
    sdk -> device: Ring=0
    Note over device: Ringer stops
	phone -> sdk: releaseLockAsync()
	sdk -> phone:
	Deactivate sdk
@enduml

@startuml
    title Mute and unmute call by user
    participant "Softphone" as phone
    participant "Jabra SDK" as sdk
    participant "Jabra Device" as device
    Actor User as user
    phone->sdk: getLockAsync()
    sdk->phone:
    Activate phone
    Note over phone: Call lock acquired
    phone->sdk: offhookAsync()
    sdk->device: OffHook=1
    note over device: Device is in call state
    ...
    user -> device: Press mute button
    device->sdk: Mute
    sdk->phone: btnPress\n(Mute)
    phone->sdk: muteAsync()
    sdk->device: Mute
    note over device: Device mutes
    ...
    user -> device: Press mute button
    device->sdk: Mute
    sdk->phone: btnPress\n(Mute)
    phone->sdk: unmuteAsync()
    sdk->device:
    note over device: Device unmutes
    ...
    phone->sdk: onhookAsync()
    sdk->device: OffHook=0
    note over device: Device no longer in call state
    phone->sdk: releaseLockAsync()
    Deactivate phone
    sdk->phone:
@enduml

@startuml
    title Hold and resume by user
    participant "Softphone" as phone
    participant "Jabra SDK" as sdk
    participant "Jabra Device" as device
    Actor User as user
    phone->sdk: getLockAsync()
    sdk->phone:
    Activate phone
    Note over phone: Call lock acquired
    phone->sdk: offhookAsync()
    sdk->device: OffHook=1
    note over device: Device is in call state
    ...
    user->device: Flash button
    device->sdk: Flash
    sdk->phone: btnPress\n(Flash)
    phone->sdk: holdAsync()
    sdk->device: Hold=1
    phone->sdk: onhookAsync()
    sdk->device: OffHook=0
    note over device: Device enters held state
    ...
    user->device: Flash button
    device->sdk: Flash
    sdk->phone: btnPress\n(Flash)
    phone->sdk: offhookAsync()
    sdk->device: OffHook=1
    phone->sdk: resumeAsync()
    sdk->device: Hold=0
    note over device: Device leaves held state\nand resumes call
    phone->sdk: onhookAsync()
    sdk->device:
    note over device: Device leaves call state
    phone->sdk: releaseLockAsync()
    Deactivate phone
    sdk->phone:
@enduml